const fs = require('fs');
const path = require('path');

const sourceFile = path.join(__dirname, 'src', 'hooks', 'use-api.ts');
const apiDir = path.join(__dirname, 'src', 'hooks', 'api');

if (!fs.existsSync(apiDir)) {
  fs.mkdirSync(apiDir, { recursive: true });
}

let content = fs.readFileSync(sourceFile, 'utf-8');

// Extract Types and Fetcher for core.ts
const coreEndIndex = content.indexOf('// SESSIONS HOOKS');
const coreContentRaw = content.substring(0, coreEndIndex);
const coreContent = `import apiClient from '@/lib/api-client';

${coreContentRaw.substring(coreContentRaw.indexOf('// ============================================================================\n// TYPES'))}

export { fetcher, supabaseApiFetcher };
`;

fs.writeFileSync(path.join(apiDir, 'core.ts'), coreContent);

// Remaining hooks
const hooksContent = content.substring(coreEndIndex);
const regex = /\/\/ ={20,}\n\/\/ (.*?)\n\/\/ ={20,}/g;

let matches = [];
let match;
while ((match = regex.exec(hooksContent)) !== null) {
  matches.push({
    title: match[1].trim(),
    index: match.index,
    length: match[0].length
  });
}

const commonImports = `import { useState, useEffect, useCallback } from 'react';
import useSWR from 'swr';
import apiClient from '@/lib/api-client';
import { projectId, publicAnonKey } from '@/utils/supabase/info';
import { fetcher, supabaseApiFetcher } from './core';

`;

let indexFile = `/**\n * Autogenerated API Hooks Index\n * Retro-compatibility layer for ARCH-001\n */\n\nexport * from './api/core';\n`;

for (let i = 0; i < matches.length; i++) {
  const current = matches[i];
  const next = matches[i + 1];
  const start = current.index + current.length;
  const end = next ? next.index : hooksContent.length;
  
  let code = hooksContent.substring(start, end).trim();
  if (!code) continue;
  
  // Format filename
  let filename = current.title
      .toLowerCase()
      .replace(/ - .*?$/, '') // remove ' - FASE 2'
      .replace(/ hooks?$/, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
      
  filename = `use-${filename}-api.ts`;
  
  // Custom corrections
  if (filename === 'use-custom-api.ts') filename = 'use-submissions-api.ts'; // CUSTOM HOOKS had submissions
  
  fs.writeFileSync(path.join(apiDir, filename), commonImports + code + '\n');
  indexFile += `export * from './api/${filename.replace('.ts', '')}';\n`;
  console.log('Created: ' + filename);
}

// Rename old backup and create new use-api.ts
fs.renameSync(sourceFile, sourceFile + '.backup');
fs.writeFileSync(sourceFile, indexFile);
console.log('Success! Refactored use-api.ts');
