module.exports = {
  content: ["./src/components/auth/LunaLogin.tsx"],
  theme: {
    extend: {
      colors: {
        sky_l: '#8ECAE6',
        teal_l: '#209EBB',
        navy: '#023047',
        'navy-light': '#0a4060',
        'navy-mid': '#0d3550',
        gold: '#FFB701',
        orange_l: '#FC8500',
        muted: '#6A9DB8',
        'muted-hi': '#A8CFE0',
        ice: '#E8F4FA',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
      },
      keyframes: {
        dropIn: { from: { opacity: '0', transform: 'translateY(-20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.94) translateY(18px)' }, to: { opacity: '1', transform: 'scale(1) translateY(0)' } },
        fadeUp: { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeRight: { from: { opacity: '0', transform: 'translateX(-12px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        pulse_dot: { '0%,100%': { opacity: '1', transform: 'scale(1)' }, '50%': { opacity: '0.3', transform: 'scale(0.7)' } },
        shimmerLine: { '0%,100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        toastPop: { to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        spin: { to: { transform: 'rotate(360deg)' } },
      },
      animation: {
        dropIn: 'dropIn 0.6s ease-out 0.15s forwards',
        scaleIn: 'scaleIn 0.6s ease-out 0.35s forwards',
        fadeUp1: 'fadeUp 0.5s ease-out 0.55s forwards',
        fadeUp2: 'fadeUp 0.4s ease-out 0.65s forwards',
        fadeUp3: 'fadeUp 0.4s ease-out 0.75s forwards',
        fadeUp4: 'fadeUp 0.4s ease-out 0.85s forwards',
        fadeUp5: 'fadeUp 0.4s ease-out 1.05s forwards',
        fadeUp6: 'fadeUp 0.4s ease-out 1.2s forwards',
        fadeRight: 'fadeRight 0.5s ease-out 0.55s forwards',
        pulse_dot: 'pulse_dot 2s ease-in-out infinite',
        pulse_fast: 'pulse_dot 1.5s ease-in-out infinite',
        shimmer: 'shimmerLine 3.5s ease-in-out infinite',
        toastPop: 'toastPop 0.35s ease forwards',
        spin: 'spin 0.8s linear infinite',
      },
    },
  },
}
