/**
 * Autogenerated API Hooks Index
 * Retro-compatibility layer for ARCH-001
 */

export * from './api/core';
export * from './api/use-sessions-api';
export * from './api/use-workouts-exercises-api';
export * from './api/use-calendar-api';
export * from './api/use-confirmations-api';
export * from './api/use-analytics-api';
export * from './api/use-reports-api';
export * from './api/use-notifications-api';
export * from './api/use-webhooks-api';
export * from './api/use-export-api';
export * from './api/use-audit-logs-api';
export * from './api/use-athlete-api';
export * from './api/use-submissions-api';
